# Generated by Django 6.0 on 2025-12-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_knowledge_base', '0002_category_article_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Выберите категорию для статьи', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='the_knowledge_base.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Необязательное описание категории', verbose_name='Описание категории'),
        ),
    ]
